### ISSUE TITLE
使用文字表情，程序自动闪退，图片表情没事

### ISSUE THREAD

**Issue by DuanxxPlus** [MemeCrafters/meme-generator#216]
![1c0190878a61b21dd6690c4d912d52d2](https://github.com/user-attachments/assets/ccd258d1-fbf0-481a-ad90-d8c87ba5a57b)
控制台这样，不报错，就直接退出，就像自动按ctrl c一样，只要已用文字的就是，比如咖波说，王境泽等等，图片的就没事。版本是最新的，现在只能回退到以前的版本

**Comment by MeetWq** [comment]
请参考 #188

**Comment by DuanxxPlus** [comment]
> 请参考 #188

多谢
