### ISSUE TITLE
猩猩扔报错找不到图片，但是实际有

### ISSUE THREAD

**Issue by DuanxxPlus** [MemeCrafters/meme-generator#218]
![f3f625b91818f77e3915a47e7d596e06](https://github.com/user-attachments/assets/c3fd00c8-3ccc-4941-8ce1-d5a229202d8a)
![f160a70a99964834bd0f16f43a26eeef](https://github.com/user-attachments/assets/3b09f839-32c6-4633-b48b-00bbea41da3f)
如图，猩猩扔报错，但图片是有的

**Comment by MeetWq** [comment]
5e9a2d3
